concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "docker-runner-ubuntu"
  url = "https://www.jvj28.com/gitlab/"
  id = 4
  token = "Y12FsCeDY7QXmx1FF8Px"
  token_obtained_at = "2023-05-07T06:27:47Z"
  token_expires_at = "9999-01-01T00:00:00Z"
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "ubuntu:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    shm_size = 0
